### PR TITLE
Added resource

### PR DESCRIPTION
**Pull request by stephanieeechang**
Added LeetCode to Coding resources for beginners section

### CODE REVIEW

**Comment by dreamtocode** [comment]
Hi @stephanieeechang 

Thanks for sending pr, I appreciate it very much. You need to create new header "Getting ready for coding Interview questions" and add this resource maybe it will be better if you add it after "Courses for advanced learners". Make sure that you resolve conflicts that this branch has by adding same resources that I merged a few minutes ago.

Have a great day!

**Comment by stephanieeechang** [comment]
Hi @dreamtocode 
Thanks for the feedback, I made changes accordingly. Let me know if there are other issues.
Have a nice day!

**Comment by dreamtocode** [comment]
Hi @stephanieeechang 

It looks good but I think hackerrank is free am I wrong ? If no than please change tag and add it make it first in that section. If not tell me and I'll merge if everything will be ok.

Thanks again!

**Comment by dreamtocode** [comment]
Hi @stephanieeechang 

Yes for sure make it free. This resources are mostly for users.

Thanks !

**Comment by georgegognadze** [comment]
Hi @stephanieeechang 

It's there, thanks.

Have a great day!

**Pull request closed without merging**
